services:  
  frontend:
    build: ./frontend/
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    depends_on:
      - backend
      
  backend:
    build: ./backend/
    volumes:
      - .:/workspace:cached
    command: sleep infinity